added some feature  hot reload
sholladay/pogo pull request #58
Opened 2021-03-24 06:13 UTC by vivekchauhan12000

this feature helps to hotreload the server with the help of single command for example " deno run --allow-read --allow-run --allow-net hotreload.ts --main=server.js "
In which server.js is the file you need to reload automatically when saved or changes been made in it.
in place of file address in command, we can also use the HTTPS way of deno after it been added in the main branch

2021-03-24 15:13 UTC, sholladay commented
Hi @vivekchauhan12000, thanks for contributing. Looks nice!

So this serves the same purpose as nodemon or pm2, right? The code doesn't seem to be connected to Pogo per se. Is there a reason you think it should live in here as opposed to being a separate module on `deno.land/x`? Have I missed something?

I am open to having an official watch mode for Pogo apps, especially if there is some benefit it can provide over a generic watch module.

2021-03-24 17:55 UTC, vivekchauhan12000 commented
Yes like nodemon but within pogo itself
I not connected to any of the pogo files to make sure if someone wants to make it react.js with pogo then it can mess up with react hot reload and if someone tries pogo first time it will make it work much easier and different from other libraries like oak, abc

2021-03-25 00:02 UTC, sholladay requested changes

2021-03-25 00:02 UTC, sholladay commented on hotreload.ts
> +  for (let i = 0; i < files.length; i++) {
`for (const file of files) {`

2021-03-25 00:02 UTC, sholladay commented on hotreload.ts
> +      const date = (await Deno.lstat(entry.path)).mtime;
Should probably use `Deno.stat()` instead of `Deno.lstat()`.

2021-03-25 03:51 UTC, vivekchauhan12000 commented on hotreload.ts
> +  await new Promise((r) => setTimeout(r, 500));
Ya  I will try and let you know

2021-05-01 03:24 UTC, sholladay commented
Hi @vivekchauhan12000. Are you still interested in getting this merged? Did you see my review above?

2022-03-10 05:33 UTC, sholladay commented
Closing due to lack of progress. But I'd love to have a tool like this merged, if anyone has time to work on it.

2022-03-10 05:33 UTC, closed without merging